### ISSUE TITLE
An real important feature

### ISSUE THREAD

**Issue by minanagehsalalma** [staz0t/hashcatch#1]
@staz0t 
If the network has wps enabled .. It would give you a lot of info.like router model number and serial number and if it's pbc or pin .

And an idea for another project is a user agent collector 
it's just a mix of karma attack and a web server to catch the user agent and the ap that it came from with both bssids and maybe deauth would be useful in that part
just like this
[Img](https://user-images.githubusercontent.com/20546638/63057764-48d4ac00-beeb-11e9-9a65-8fe9e95f733b.png)
I think it can be done without a webserver as the APS send the user agent in the background... And of course store that info in a db

**Comment by staz0t** [comment]
Hello,
Thanks for your suggestions!
Yes, I'm soon going to implement pixiedust attack in the tool. I've mentioned it in the "Features to be added" section of README.

Regarding the user agent collector, yes the attack seems feasible. But I fail to understand the purpose of collecting user agents. Can you please elaborate on that?

**Comment by minanagehsalalma** [comment]
> Hello,
> Thanks for your suggestions!
> Yes, I'm soon going to implement pixiedust attack in the tool. I've mentioned it in the "Features to be added" section of README.
> 
> Regarding the user agent collector, yes the attack seems feasible. But I fail to understand the purpose of collecting user agents. Can you please elaborate on that?

You don't  need pixe dust to get the model number  .  You can get it just using wps scan tool .. or wair cut in windows  even wifi info view from nirsoft can do it ..

Useragents = phone model numbers and even other devices model numbers 

It will give you a better understanding of the devices around  you and of course  finding the vunrable one based on their os version from the useragent .. 
Abd will also will help tracking these devices and building a small map of networks they use. ..  that can help cracking more than one handshake with similar  or shared passwords 
..
In a couple of words it just gives more info about what can you do and the Surrounding environment.

**Comment by staz0t** [comment]
Yes, that's a valid point. I'll have this on my list of future features. Thank you!

**Comment by minanagehsalalma** [comment]
@staz0t  Great ..  Keep me updated :)
