### ISSUE TITLE
Can't install hashcat-utils on raspberry pi

### ISSUE THREAD

**Issue by raymondbo1234** [staz0t/hashcatch#11]
I'm running kali on a raspberry pi zero w with nexmon patch. When I run the setup of hashcatch. It says hashcat-utils dependency is missing. But I can't find hashcat-utils in the repository. Any help with the issue please?

**Comment by staz0t** [comment]
Hashcat-utils is not available in apt repositories. You have to download and install from their GitHub.
But, hashcatch's .deb package does it automatically for you.

So, your options are, either to download and install hashcat-utils from their GitHub, or install hashcatch using the .deb package.
