### ISSUE TITLE
Hashcatch not starting

### ISSUE THREAD

**Issue by tomjones1111** [staz0t/hashcatch#12]
Hi guys, I am running into an issue getting hashcatch to run. all prerequisites are installed.

This is screen I am getting:

> [*] Starting hashcatch setup
ls: cannot access '/usr/share/hashcatch/handshakes/': No such file or directory
[*] Enter your wireless interface: wlan1
[*] Trying to set the given interface to monitor mode
[+] The adapter is working in monitor mode!
./hashcatch: line 88: /etc/hashcatch/hashcatch.conf: No such file or directory
[*] All necessary packages are found installed
[*] Done

Please help.
Running on 4.19.0-kali4-amd64

Thanks!

**Comment by zMrDevJ** [comment]
Hi,

I guess I'm having similar issues.
I'm running the script on the latest Kali docker image on Fedora30, as superuser.
I installed all the requirements but the script doesn't seem to create its folders and files on the first run `$: sudo ./hashcatch --setup`:

>[*] Starting hashcatch setup
ls: cannot access '/usr/share/hashcatch/handshakes/': No such file or directory
[*] Enter your wireless interface: <my_interface>
[*] Trying to set the given interface to monitor mode
[+] The adapter is working in monitor mode!
./hashcatch: line 88: /etc/hashcatch/hashcatch.conf: No such file or directory
[*] All necessary packages are found installed
[*] Done

And when I start the script `$: sudo ./hashcatch`:
 
>grep: /etc/hashcatch/hashcatch.conf: No such file or directory
[-] Essential file(s) missing. Run with --setup and try again!`

I tried to create the `hashcatch.conf` file and the `hashcatch` folder manually before running the script but nothing changes.

Any suggestions?

**Comment by tomjones1111** [comment]
The .conf file should be empty?

**Comment by tomjones1111** [comment]
> Hi,
> 
> I guess I'm having similar issues.
> I'm running the script on the latest Kali docker image on Fedora30, as superuser.
> 
> [I removed the console report in order to avoid confusion]
> ### Update
> 
> By removing the created folders and creating them again (without the .conf file) the setup runs properly and the script will work.
> So I suggest @tomjones1111 to create the folders manually before running the setup, hope it will help!

So I created both directories form my first post. Now i am getting this in the console:

[*] Starting hashcatch setup
[*] Enter your wireless interface: wlan1
[*] Trying to set the given interface to monitor mode
[+] The adapter is working in monitor mode!
[*] All necessary packages are found installed
[*] Done

Nothing else happens after that. Isnt it supposed to be scanning through networks?
Please help!

Thanks!

**Comment by zMrDevJ** [comment]
Well, the setup step seems to be properly done.

Now you just have to run `sudo ./hashcatch` in order to use the script.

**Comment by staz0t** [comment]
Hey guys,

Sorry for my delayed response.
There could be some environmental issues, since I have never tested hashcatch in a docker.
So, the setup does the following.
1. Creates /etc/hashcatch/hashcatch.conf file
2. Creates /usr/share/hashcatch/db file and /usr/share/hashcatch/handshakes directory.

So just in case the setup, for some reason failed to do so, you can create these files manually and run sudo ./hashcatch and it should work properly. Let me know how it goes.

Also, have you tried installing with the .deb package from the releases?

**Comment by zMrDevJ** [comment]
> Hey guys,
> 
> Sorry for my delayed response.
> There could be some environmental issues, since I have never tested hashcatch in a docker.
> So, the setup does the following.
> 
> 1. Creates /etc/hashcatch/hashcatch.conf file
> 2. Creates /usr/share/hashcatch/db file and /usr/share/hashcatch/handshakes directory.
> 
> So just in case the setup, for some reason failed to do so, you can create these files manually and run sudo ./hashcatch and it should work properly. Let me know how it goes.
> 
> Also, have you tried installing with the .deb package from the releases?
> 
> And tomjones1111, as suggested by zMrDevJ, the setup has completed successfully in your case. You can proceed to run hashcatch and it will work fine.

Thank you for the reply! 
In my case, I solved the issues by just creating the needed path folders (as also you said), so I can confirm that your script works on a Docker container within Kali Linux inside, too. 😄

**Comment by staz0t** [comment]
> > Hey guys,
> > Sorry for my delayed response.
> > There could be some environmental issues, since I have never tested hashcatch in a docker.
> > So, the setup does the following.
> > 
> > 1. Creates /etc/hashcatch/hashcatch.conf file
> > 2. Creates /usr/share/hashcatch/db file and /usr/share/hashcatch/handshakes directory.
> > 
> > So just in case the setup, for some reason failed to do so, you can create these files manually and run sudo ./hashcatch and it should work properly. Let me know how it goes.
> > Also, have you tried installing with the .deb package from the releases?
> > And tomjones1111, as suggested by zMrDevJ, the setup has completed successfully in your case. You can proceed to run hashcatch and it will work fine.
> 
> Thank you for the reply!
> In my case, I solved the issues by just creating the needed path folders (as also you said), so I can confirm that your script works on a Docker container within Kali Linux inside, too.

Awesome! Thank you :)
