### ISSUE TITLE
Can't run hashcatch on pi w zero

### ISSUE THREAD

**Issue by spideyroc1** [staz0t/hashcatch#13]
Hey so while running hashcatch on raspbian, on my raspberry pi zero W it can never connect the wifi device to monitor mode,

doing the command
"iw list"
shows the supported interfaces of the pi's wifi card
monitor mode doesn't show up
available ones are: 
IBSS
MANAGED
AP
P2P-CLIENT
P2P-GO
PDP-DEVICE
is there a way to fix?

**Comment by meunlo** [comment]
Not sure if this applies. https://null-byte.wonderhowto.com/how-to/enable-monitor-mode-packet-injection-raspberry-pi-0189378/

**Comment by spideyroc1** [comment]
Well i was able to "fix" this issue by using a seperate wifi adapter
now the problem is 
[!] The following packages are missing. Please ensure that you have installed them properly before starting hashcatch
	hashcat-utils
but it is indeed installed

using the command in the script to detect if installed i get proper output:
pi@raspberrypi:~/hashcatch $ command -v cap2hccapx
/home/pi/hashcat-utils-1.9/bin/cap2hccapx

**Comment by staz0t** [comment]
Hey,
Can you run the command `cap2hccapx` and post the output here?

And regarding your first issue of not being able to put your raspberry pi in monitor mode, it must be because the adaptor doesn't support monitor mode. You can use aircrack-ng to test if it supports packet injection.

**Comment by spideyroc1** [comment]
![image](https://user-images.githubusercontent.com/11247590/65658522-bf39f300-dfed-11e9-9c1b-8c6ed59994cd.png)

**Comment by spideyroc1** [comment]
and yes i discovered there was no way for the monitor mode on that so i used an old wifi dongle i had laying around which works with monitor

**Comment by spideyroc1** [comment]
so because i was running it as sudo it was unable to find it in the path
my solution which is now working:
sudo -E env "PATH=$PATH" ./hashcatch

**Comment by staz0t** [comment]
There is a way to change the settings globally to make `sudo` use the same PATH variable.

https://unix.stackexchange.com/questions/83191/how-to-make-sudo-preserve-path

**Comment by natur3kid** [comment]
Change the rpi0w kernel to the one from re4son (nullbyte link) and then monitor mode indeed WILL work.

**Comment by spideyroc1** [comment]
intereseting, installed the kernel and am still unable to connect the onboard wifi module to monitor mode

**Comment by haroonalhadisk** [comment]
please tell me how to add path the issue still persists as i cannot seem to install hashcat-utils only binaries are available and the hascath seems to say the same thing again and again. eaven after adding path.
