### ISSUE TITLE
Packages are missing - hashcat-utils

### ISSUE THREAD

**Issue by Benderz** [staz0t/hashcatch#14]
On my Kali for Raspberry Pi Zero W I got: 
[!] The following packages are missing. Please ensure that you have installed them properly before starting hashcatch
        hashcat-utils

Where are no hashcat-utils in Kali repository, so I downloaded and compiled hashcat-utils and run hashcatch again - same message.
How to show hashcatch path to my folder /root/hashcat-utils/bin/ ?

**Comment by staz0t** [comment]
Hashcatch uses cap2hccapx from hashcat-utils. So check if the location of cap2hccapx is there in PATH.

**Comment by Benderz** [comment]
Please, tell me how add my folder "/root/hashcat-utils/bin/" to PATH correctly.

**Comment by staz0t** [comment]
https://unix.stackexchange.com/questions/26047/how-to-correctly-add-a-path-to-path

**Comment by Lvc4** [comment]
hello i have done this but nothing changes
