### ISSUE TITLE
Hashcat-utils 

### ISSUE THREAD

**Issue by scor1n** [staz0t/hashcatch#18]
I have read all other reports and solutions to this problem but I still get the problem. Might be because I dont understand the solutions. Can you help me out, thanks 
![image](https://user-images.githubusercontent.com/64503655/80549125-6454e980-898a-11ea-8772-0d3d2979defd.jpg)

**Comment by staz0t** [comment]
Hashcatch throws this error when it could not find the necessary binary/binaries in the PATH. It checks that by using the `command -v {name of the command}` command for Debian based distros.

Hashcatch needs cap2hccapx from hashcat-utils package. So, what you have to make sure of, is that you have cap2hccapx in your PATH.

Just use the following command to check that.
`command -v cap2hccapx`

If you get any output from the last command, it means that the location of the binary is added to PATH, and hashcatch would not throw any errors. It is entirely possible that you have installed hashcat-utils, but it has not been added to the PATH yet.

So, for anyone who's facing this issue, just make sure that the locations of the binaries are added to PATH. You can simply type in the command, or use `command -v {name of the command}` (for Debian based distros) to check that.

Here's the list of package missing errors and which binary is actually missing from PATH.
aircrack-ng -> aircrack-ng
hashcat-utils - > cap2hccapx
hcxtools -> wlanhcxinfo
jq -> jq

Hope this helps!

**Comment by staz0t** [comment]
Also, the error also says that your network adapter could not be set to monitor mode. The network adapter you are using should have the capability to work in monitor mode.

**Comment by scor1n** [comment]
I will try that and let you know how it goes. Where is PATH?

**Comment by staz0t** [comment]
If you're unsure of what PATH is, I think you should become familiar with Linux first.

**Comment by scor1n** [comment]
I have put it in path and it still doesn’t recognize it

**Comment by staz0t** [comment]
Did you try the `command -v cap2hccapx` command I suggested? Or did you try to run `cap2hccapx` from your terminal?

**Comment by scor1n** [comment]
I have tried it and I have looked up how to troubleshoot this but still nothing 
I thank you for your time trying to help me, I really appreciate it 
![image](https://user-images.githubusercontent.com/64503655/80607911-0ebd2300-8a04-11ea-800e-7f4e87d3cc04.jpg)
