### ISSUE TITLE
Hashcatch on Raspberry Pi - cannot install hashcat-utils

### ISSUE THREAD

**Issue by mroxso** [staz0t/hashcatch#21]
I'm currently facing the issue that my Raspberry Pi won't setup because it tells me to install hashcat-utils. But how to install that the proper way for hashcatch and Raspberry Pi?

`[!] The following packages are missing. Please ensure that you have installed them properly before starting hashcatch - hashcat-utils
`

I tried to download hashcat from GitHub and compiled it manually (sudo make && sudo make install). That install hashcat for me. But it seems like Hashcatch does not like this way?

Any help please?

**Comment by staz0t** [comment]
The error message is pretty clear. You have to install hashcat-utils and make sure it's on the PATH. I've already addressed this multiple times in other issues.

**Comment by mroxso** [comment]
Sorry, but I already tried that. Now there is only the following error:
` \033[1;33m[!] The following packages are missing. Install them and try again!\033[0m`

**I fixed my problem. The problem was that i set the PATH to hashcat-utils to a path where the user had no access to (another home directory). After fixing this, it seems like it's working now. Thank you**
