### ISSUE TITLE
[-] Essential file(s) missing. Run with --setup and try again!

### ISSUE THREAD

**Issue by salova322** [staz0t/hashcatch#26]
![Screenshot_2021-09-20-00-47-37-813_com termux](https://user-images.githubusercontent.com/33322582/133941015-f2627788-f3c7-4122-9c30-a4d8d31fbe15.jpg)

I'm on kali. What is the problem?

**Comment by dbzx6r** [comment]
you need to run sudo ./hashcatch --setup

**Comment by salova322** [comment]
> you need to run sudo ./hashcatch --setup

Above i run that and it said "done"

You couldn't see an entire screenshot?
