### ISSUE TITLE
test mode monitor before continue

### ISSUE THREAD

**Issue by 0x25** [staz0t/hashcatch#4]
hello after interface grep you can add this lines

> mode=$(iwconfig wlan0 | head -n 1 | awk -F" " '{print $4}' | awk -F":" '{print $2}')  
> if [ "$mode" != "Monitor" ]; then  
>   echo "Start mode monitor on [$interface]"  
>   airmon-ng check kill  
>   airmon-ng start $interface  
> else  
>   echo "Mode Monitor enable"  
> fi  

to check mode monitor

**Comment by staz0t** [comment]
Hello,

airodump-ng automatically sets the adapter to monitor mode when started, in all the devices I have tested on. If you have ever faced a situation where you had to enable monitor mode to get it working, please let me know.

However, I can use these commands in setup.sh to check if the given interface is capable of working in monitor mode.
There's also aireplay-ng --test command which can do this job. Do you think that will be a better choice?

**Comment by staz0t** [comment]
Hey,
I have added code to check monitor mode in the setup script.
Thank you for your suggestion!
