### ISSUE TITLE
cap2hccapx deprecated

### ISSUE THREAD

**Issue by 0x25** [staz0t/hashcatch#5]
hello 

cap2hccapx is deprecated and not present in hxtools
use hcxpcaptool instead

**Comment by ZerBea** [comment]
get full advantage of hcxpcaptool (-E -I -U) in combination with hcxdumptool (attack vector PMKID, attack vector AP-LESS, attack vector EAP)

$ hcxpcaptool -o test.hccapx -E wordlist -I wordlist *.pcapng
reading from example1.pcapng
summary capture file:                           
file name........................: example1.pcapng
file type........................: pcapng 1.0
file os information..............: Linux 4.19.65-1-ARCH
file application information.....: hcxdumptool 5.1.7
network type.....................: DLT_IEEE802_11_RADIO (127)
endianness.......................: little endian
read errors......................: flawless
minimum time stamp...............: 19.10.2017 15:29:42 (GMT)
maximum time stamp...............: 19.10.2017 15:33:36 (GMT)
packets inside...................: 9
skipped packets (damaged)........: 0
packets with GPS data............: 0
packets with FCS.................: 0
association requests.............: 3
EAPOL packets (total)............: 5
EAPOL packets (WPA2).............: 5
EAP packets......................: 1
found............................: EAP type ID
best handshakes (total)..........: 1 (ap-less: 0)

summary output file(s):
1 handshake(s) written to test.hccapx
message pair M32E2...............: 1

reading from example2.pcapng
summary capture file:                           
file name........................: example2.pcapng
file type........................: pcapng 1.0
file hardware information........: armv6l
file os information..............: Linux 4.19.65-1-ARCH
file application information.....: hcxdumptool 5.1.7
network type.....................: DLT_IEEE802_11_RADIO (127)
endianness.......................: little endian
read errors......................: flawless
minimum time stamp...............: 11.08.2019 17:57:00 (GMT)
maximum time stamp...............: 11.08.2019 17:58:03 (GMT)
packets inside...................: 10
skipped packets (damaged)........: 0
packets with GPS data............: 0
packets with FCS.................: 0
beacons (total)..................: 2
probe requests...................: 1
association requests.............: 2
association responses............: 1
authentications (OPEN SYSTEM)....: 1
authentications (BROADCOM).......: 1
EAPOL packets (total)............: 3
EAPOL packets (WPA2).............: 3
best handshakes (total)..........: 1 (ap-less: 0)

summary output file(s):
1 handshake(s) written to test.hccapx
message pair M12E2...............: 1

reading from example3.pcapng
summary capture file:                           
file name........................: example3.pcapng
file type........................: pcapng 1.0
file os information..............: Linux 4.19.65-1-ARCH
file application information.....: hcxdumptool 5.1.7
network type.....................: DLT_IEEE802_11_RADIO (127)
endianness.......................: little endian
read errors......................: flawless
minimum time stamp...............: 26.05.2017 08:05:46 (GMT)
maximum time stamp...............: 26.05.2017 09:04:13 (GMT)
packets inside...................: 6
skipped packets (damaged)........: 0
packets with GPS data............: 0
packets with FCS.................: 0
beacons (total)..................: 2
probe responses..................: 2
EAPOL packets (total)............: 2
EAPOL packets (WPA2).............: 2
best handshakes (total)..........: 1 (ap-less: 1)

summary output file(s):
1 handshake(s) written to test.hccapx
message pair M12E2...............: 1

$ hashcat -m 2500 test.hccapx wordlist
hashcat (v5.1.0-1397-g7f4df9eb) starting...
Session..........: hashcat
Status...........: Cracked
Hash.Name........: WPA-EAPOL-PBKDF2
Hash.Target......: test.hccapx
Time.Started.....: Mon Aug 26 15:40:07 2019 (1 sec)
Time.Estimated...: Mon Aug 26 15:40:08 2019 (0 secs)
Guess.Base.......: File (wordlist)
Guess.Queue......: 1/1 (100.00%)
Speed.#1.........:      613 H/s (3.05ms) @ Accel:16 Loops:512 Thr:64 Vec:1
Recovered........: 3/3 (100.00%) Digests, 3/3 (100.00%) Salts
Progress.........: 54/54 (100.00%)
Rejected.........: 0/54 (0.00%)
Restore.Point....: 0/18 (0.00%)
Restore.Sub.#1...: Salt:2 Amplifier:0-1 Iteration:0-1

**Comment by staz0t** [comment]
Hey,

I'm using cap2hccapx from hashcat-utils and not from hcxtools. 
And I'm working on using hcxdumptool and hcxpcaptool for PMKID attack in hashcatch, as mentioned in the features to be added section of README.

So, when i include that, I'll make sure I use hcxpcaptool instead of cap2hccapx.
I'm closing this issue now, thank you for your suggestions!
