### ISSUE TITLE
filter airodump 

### ISSUE THREAD

**Issue by 0x25** [staz0t/hashcatch#6]
hello

try crack handshack on OPN wifi is usless.
you can add filter

> timeout --foreground 3 airodump-ng "$interface" -t wpa -w /tmp/hc_out --output-format csv &> /dev/null

**Comment by staz0t** [comment]
Hey,

Sure, that's a valid point. Would you like to make the change yourself and give me a pull request?

**Comment by staz0t** [comment]
Hey,
I've made the added the filter to the script myself. Thank you for your suggestion!
