### ISSUE TITLE
macOS - en0 monitor mode

### ISSUE THREAD

**Issue by JasonLeeH** [staz0t/hashcatch#9]
"[-] Could not set the given wireless adapter to monitor mode!"

All of the pre-requisite software runs fine in macOS so it seems ( I could be wrong ) that macOS support should be possible. I look forward to future updates. Thanks for all the hard work.

![image](https://user-images.githubusercontent.com/6761181/64068998-e24fcd80-cc0e-11e9-9880-8d092eb228da.png)

Using macOS version 10.14.6 (18G87).

**Comment by meunlo** [comment]
What is your adapter?

**Comment by JasonLeeH** [comment]
` en0:`
  `Card Type:	AirPort Extreme  (0x14E4, 0x117)`
  `Firmware Version:	Broadcom BCM43xx 1.0 (7.77.61.2 AirPortDriverBrcmNIC-1305.8)`

Not using an "adapter", per se. I do have an old Alfa card, but it is incompatible with 64-bit systems. I'm able to use sniff on bettercap using the built-in card.

**Comment by staz0t** [comment]
Hey, can you run

airodump-ng --test en0

And show me the output? That will be really helpful for me to look into the problem.

**Comment by JasonLeeH** [comment]
`MBA:~ jason$ airodump-ng --test en0`

`airodump-ng: unrecognized option '--test'`

**These are my options:**

Airodump-ng 1.5.2  - (C) 2006-2018 Thomas d'Otreppe
  https://www.aircrack-ng.org

  usage: airodump-ng <options> <interface>[,<interface>,...]

  Options:
      --ivs                 : Save only captured IVs
      --gpsd                : Use GPSd
      --write      <prefix> : Dump file prefix
      -w                    : same as --write 
      --beacons             : Record all beacons in dump file
      --update       <secs> : Display update delay in seconds
      --showack             : Prints ack/cts/rts statistics
      -h                    : Hides known stations for --showack
      -f            <msecs> : Time in ms between hopping channels
      --berlin       <secs> : Time before removing the AP/client
                              from the screen when no more packets
                              are received (Default: 120 seconds)
      -r             <file> : Read packets from that file
      -x            <msecs> : Active Scanning Simulation
      --manufacturer        : Display manufacturer from IEEE OUI list
      --uptime              : Display AP Uptime from Beacon Timestamp
      --wps                 : Display WPS information (if any)
      --output-format
                  <formats> : Output format. Possible values:
                              pcap, ivs, csv, gps, kismet, netxml, logcsv
      --ignore-negative-one : Removes the message that says
                              fixed channel <interface>: -1
      --write-interval
                  <seconds> : Output file(s) write interval in seconds
      --background <enable> : Override background detection.

  Filter options:
      --encrypt   <suite>   : Filter APs by cipher suite
      --netmask <netmask>   : Filter APs by mask
      --bssid     <bssid>   : Filter APs by BSSID
      --essid     <essid>   : Filter APs by ESSID
      --essid-regex <regex> : Filter APs by ESSID using a regular
                              expression
      -a                    : Filter unassociated clients

  By default, airodump-ng hops on 2.4GHz channels.
  You can make it capture on other/specific channel(s) by using:
      --ht20                : Set channel to HT20 (802.11n)
      --ht40-               : Set channel to HT40- (802.11n)
      --ht40+               : Set channel to HT40+ (802.11n)
      --channel <channels>  : Capture on specific channels
      --band <abg>          : Band on which airodump-ng should hop
      -C    <frequencies>   : Uses these frequencies in MHz to hop
      --cswitch  <method>   : Set channel switching method
                    0       : FIFO (default)
                    1       : Round Robin
                    2       : Hop on last
      -s                    : same as --cswitch
      --help                : Displays this usage screen

**Comment by JasonLeeH** [comment]
airodump-ng doesn't work on macOS apparently: https://apple.stackexchange.com/questions/117843/equivalent-of-airodump-ng-for-max-os-x

**Comment by meunlo** [comment]
But this guy got it working
After much frustration with this same problem I found a way to actually use Airodump on my Mac terminal. What I realized is that all of the files that I can successfully execute are located in the directory path

/usr/local/bin/

And it turns out that Airodump was actually on my computer, it was just stored in the path

/usr/local/sbin

And I was unable to execute it from that path. All I did was move Airodump from the /usr/local/sbin path to the /usr/local/bin path and it now works great! I was going crazy for hours and it was that simple

**Comment by JasonLeeH** [comment]
It "works", but it doesn't work. It faces the same issue: it doesn't recognize the wireless interface.

`MBA:~ jason$ airodump-ng en0`
`Failed initializing wireless card(s): en0`

**Comment by staz0t** [comment]
One other guy in Reddit also had issues with setting up the dependencies in os x. Unfortunately, I don't have access to an os x machine to test it and help you out.
Feel free to update here when you find a way to get airodump-ng working in os x.

I'll try to add native support to os x by replacing airodump-ng with airport in future updates. As of now, I'm adding this as a known issue.

**Comment by nuclear-bean** [comment]
So did anyone managed to get clear answer on whether airodump-ng can or cannot be used on MacOS?

**Comment by josephosan** [comment]
Using the Wireless Diagnostics Sniffer tool is a great option. It allows you to capture traffic on a specific channel and saves the results in a .pcap format in the /var/tmp folder, which you can then open with Wireshark. it might not be as flexible as using airdorp on command line, but it works. 

I tried to create a symlink for the AirDrop binary located at:
/System/Library/PrivateFrameworks/Apple80211.framework/Versions/Current/Resources/airport
and link it to my bin folder, but it failed with an error:
➜  ~ sudo airport sniff 1
WARNING: The airport command line tool is deprecated and will be removed in a future release.
For diagnosing Wi-Fi related issues, use the Wireless Diagnostics app or wdutil command line tool.

**Comment by dart8888** [comment]
![Image](https://github.com/user-attachments/assets/9b8e5eda-26ea-43cf-81da-4087312f807b)
![Image](https://github.com/user-attachments/assets/c9eade85-22f7-42ff-a2ed-4b2ebf083a93)
![Image](https://github.com/user-attachments/assets/c417b179-4180-46b9-b16f-577a3abcf429)
![Image](https://github.com/user-attachments/assets/63e74fdd-750c-4823-895e-62206c04cad5)
Hashcatch не видит режим монитора, хотя он включается и видит сети.
